import { Geist, Geist_Mono } from "next/font/google";
import { Libre_Caslon_Display } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import FloatingButtons from "./components/FloatingButtons";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const libreCaslon = Libre_Caslon_Display({
  variable: "--font-libre-caslon",
  subsets: ["latin"],
  weight: ["400"],
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body
      style={{ fontFamily: 'Playfair Display' }}
        className={`${geistSans.variable} ${geistMono.variable} ${libreCaslon.variable} font-[var(--font-libre-caslon)] antialiased`}
      >
        <Navbar />
        {children}
         {/* <ScrollToTopButton /> */}
         {/* <FloatingButtons /> */}
        <Footer />
      </body>
     

    </html>
  );
}
